### ISSUE TITLE
Command 'tako80 example' fails

### ISSUE THREAD

**Issue by ahungry** [pistacchio/tako80#10]
Command 'tako80 example' fails:

I attempt to run as such (following the guide on the website):

```
λ archPad tako80-example → tako80 example                                                                                                                                                     
_http_client.js:125
      throw new TypeError('Request path contains unescaped characters');
      ^

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:125:13)
    at TunnelingAgent.request (http.js:39:10)
    at TunnelingAgent.createSocket (/usr/lib/node_modules/tako80/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/usr/lib/node_modules/tako80/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
    at TunnelingAgent.addRequest (/usr/lib/node_modules/tako80/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
    at new ClientRequest (_http_client.js:272:16)
    at Object.request (http.js:39:10)
    at Object.request (https.js:233:15)
    at Request.start (/usr/lib/node_modules/tako80/node_modules/npm/node_modules/request/request.js:583:30)
    at Request.end (/usr/lib/node_modules/tako80/node_modules/npm/node_modules/request/request.js:1237:28)
```

**Comment by pistacchio** [comment]
Hi ahungry
can you tell me the exact path where you're trying to run it? is it possible that the path contains "strange" characters like not ascii chars or spaces?
Can you try running tako80 example simply in /tmp?

Thanks

**Comment by LexiBigCheese** [comment]
this actually looks like a problem to do with receiving stuff from the
internet

**Comment by ahungry** [comment]
it fails in /tmp as well.  the previous example was in /home/mcarter/src

**Comment by LexiBigCheese** [comment]
Just as i thought, it's to do with the internet. look at where it's coming
from.

**Comment by ahungry** [comment]
Ok, it seems it is something to do with how tako80 runs the example command (is it relying on npm to go and fetch anything?) when a local proxy server is being used.

This works:

```
HTTPS_PROXY='' HTTP_PROXY='' tako80 example
```

While having those set to something like 'http://localhost:8118' (for Privoxy) will result in the error.

Similar issue here:  https://stackoverflow.com/questions/18006179/typeerror-request-path-contains-unescaped-characters

**Comment by LexiBigCheese** [comment]
that's what i was trying to say. anyway this isn't a problem with tako80.
that's for sure.

**Comment by pistacchio** [comment]
I could reproduce it by turning off my internet connection. I should handle the absence of connection gracefully, thanks for pointing it out. It will be done in the next release :)
